name: Build and Release APK

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: "Versión automática con pruebas + build APK"
