name: Build, Test and Release APK

on:
  push:
    branches: [develop, release, main]
  pull_request:
    branches: [develop, release]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  release:
    name: Publish GitHub Release
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Fetch Git tags
        run: git fetch --tags

      - name: Determine next version
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0")
          echo "Latest tag: $latest_tag"
          number=${latest_tag#v}
          next=$((number + 1))
          echo "next_version=v$next" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.next_version }}
          name: Release ${{ env.next_version }}
          files: app-release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

